from book import book
from user import user

llibre1 =  book ("El señor de los anillos", "J. R. R. Tolkien", "1978", "Blanda", "576", "Ediciones Minotauro")
llibre1.salutacio()
print("----------------------------------------------------------")
llibre1.setTapa("Dura")
llibre1.salutacio()
print("----------------------------------------------------------")
llibre2 =  book ("El Principito", "Antoine de Saint-Exupéry", "1951", "Blanda", "180", "Emecé Editores")
llibre2.salutacio()
print("----------------------------------------------------------")
llibre2.setPagines("120")
llibre2.salutacio()
print("----------------------------------------------------------")
user1 =  user ("Adria", "García", "20", "03/06/2002", "53838982F", "Dona")
user1.salutacio()
print("----------------------------------------------------------")
user1.setGenere("Home")
user1.salutacio()
print("----------------------------------------------------------")
user2 =  user ("Marc", "Cuzcano", "30", "09/03/2004", "74398516R", "Home")
user2.salutacio()
print("----------------------------------------------------------")
user2.setEdad("18")
user2.salutacio()
